using Overlayer.Tag.Core;
using System;

namespace Overlayer.Module.KeyViewer.Tag;

// Count evaluation that cannot go missing: unlike the old per-profile JS
// helpers (a Script/*.js file that had to load and register first), these
// tags are compiled into the module assembly and resolve on every frame.
// Press edge detection and persistence both live in KvCountStore, so per-key
// and total evaluations share one state table and can never double-count.
//
// Template forms (generated by the importer):
//   Held text:  (Tag.KV_IsKeyHeld("A") ? ("..." + Tag.KV_Count("PREFIX","A") + ...) : (...))
//   Total only: Tag.KV_Count("PREFIX","")
//   Reset:      Tag.KV_ResetCounts("PREFIX")
public static class KvCountTags {
    [Tag(Name = "KV_Count", Desc = "[KeyViewer] Press count for the given key of the given import (edge-triggered). Ex) {KV_Count:KeyViewer_abc1234_MyProfile,A}")]
    public static int Count(string prefix, string code) {
        if (string.IsNullOrEmpty(prefix)) return 0;
        if (string.IsNullOrEmpty(code)) {
            return Import.KvCountStore.Total(prefix);
        }
        bool held;
        try {
            held = KeyViewerInput.IsKeyHeld(code);
        } catch {
            held = false;
        }
        return Import.KvCountStore.Feed(prefix, code, held);
    }

    [Tag(Name = "KV_ResetCounts", Desc = "[KeyViewer] Resets all press counts of the given import (persisted totals too). Ex) {KV_ResetCounts:KeyViewer_abc1234_MyProfile}")]
    public static int Reset(string prefix) {
        if (string.IsNullOrEmpty(prefix)) return 0;
        Import.KvCountStore.Reset(prefix);
        return 0;
    }
}
